Include ModSecurity dependencies and build for Dikastes [WAF]
projectcalico/go-build pull request #353
Opened 2021-11-29 17:12 UTC by StevenTigera

2021-11-29 18:13 UTC, fasaxc requested changes
Couple of minor points from me.  Does modsec depend on openssl?  ( see the libcurl4-openssl dependency)  If so, it might have an impact on @caseydavenport 's FIPS work.

2021-11-29 18:13 UTC, fasaxc commented on scripts/modsec.sh
> +make install
If the files in the ModSecurity dir are not needed after install then you should delete the directory.  Otherwise all the intermediate object files will be stored in the docker image

2021-11-29 18:13 UTC, fasaxc commented on scripts/modsec.sh
> +git checkout ${MODSEC_VERSION:-v3.0.6}
+1 for pinning the version.

2021-11-30 13:09 UTC, StevenTigera commented on Dockerfile.amd64
> +        apt-utils autoconf automake build-essential \
Resolved in commit 194a7ba60538e0a3303f1a31386912c4eecd4db5

2021-11-30 13:09 UTC, StevenTigera commented on scripts/modsec.sh
> +make install
Resolved in commit 194a7ba60538e0a3303f1a31386912c4eecd4db5

2021-12-01 11:04 UTC, fasaxc approved these changes
LGTM.

2021-12-07 09:12 UTC, merged