Build and add `lipo` from Apple's cctools for making universal binaries
projectcalico/go-build pull request #551
Opened 2024-04-03 19:08 UTC by danudey

We currently build amd64 and arm64 binaries for macOS. Using Apple's `lipo` tool, we can build a universal binary which will run natively on both arm64 and amd64 macs.

2024-04-03 20:56 UTC, hjiawei commented on Dockerfile
> +        make -j12 -C libmacho && \
Suggested -j4. We build on a 4-core semaphore VM. -j12 will over schedule make progress and may cause extra scheduling/synchronization overheads.

2024-04-03 20:57 UTC, hjiawei commented on Dockerfile
> +    fi
Cleanup add intermediate build objects. It is better to build in a temporary folder and delete it after binaries are copied.

2024-04-03 20:59 UTC, hjiawei requested changes
Why do we build it from source? Is it not in any UBI or Rocky repositories? Also see comments online.

2024-04-11 17:38 UTC, danudey commented on Dockerfile
> +        make -j12 -C libmacho && \
Will fix this, thanks for the catch!

2024-04-11 17:39 UTC, danudey commented on Dockerfile
> +    fi
On line 135 we start this RUN with `RUN --mount=type=tmpfs,target=/tmp/cctools-port`, which creates a tmpfs directory at the target location. We build there, and the tmpfs is cleaned up automatically when this build stage is over so we don't have to worry about manually cleaning up.

2024-04-11 17:48 UTC, danudey commented
> Why do we build it from source? Is it not in any UBI or Rocky repositories? Also see comments online.

I have not been able to find a build of these tools in any binary repositories (neither for UBI/Rocky nor Ubuntu), nor a pre-built Docker image for the project. Given that and given how quickly we can build it, I opted to compile a version for our use.

2024-04-11 17:56 UTC, danudey commented
Nevermind me, apparently LLVM has included `lipo` as a utility for... a long time.

2024-04-11 17:56 UTC, closed without merging