add CLEANUPLEVEL arg for image-base
projectcalico/go-build pull request #618
Opened 2024-12-18 10:31 UTC by aaaaaaaalex

`make BASE_CLEANUPLEVEL=unstripped image-base` Generates an image which is scannable,

e.g. `trivy image calico/base:latest-amd64`.

`make BASE_CLEANUPLEVEL=stripped image-base` , or just `make image-base` generates the usual image with clean FS.

Make/Docker arg `UBIBASE` allows injection of a different image to build from.

Arg `(BASE_)PKGMAN` allows adjustment of pkgmanager binary name - useful if say, using DNF rather than MicroDNF. Necessary when using non-minimal UBI.

2024-12-18 14:33 UTC, fasaxc commented on Makefile
> +UBIBASE ?= registry.access.redhat.com/ubi8/ubi-minimal:latest
```suggestion
BASE_BASE_IMAGE ?= registry.access.redhat.com/ubi8/ubi-minimal:latest
```
Bit of a stutter, but would align with the args below?

2024-12-18 14:33 UTC, fasaxc commented on Makefile
> +BASE_CLEANUPLEVEL ?= stripped
```suggestion
BASE_CLEANUP_LEVEL ?= stripped
```
I'd split those words

2024-12-18 14:33 UTC, fasaxc commented on base/Dockerfile
> +FROM scratch AS intermediate-stripped
Is this intermediate one needed?  Seems to duplicate source-stripped (or source-stripped could pull from ubi?

No licenses copied into source-unstripped?  Is that because they're already there?

Worth comments explaining these details so next maintainer doesn't need to ask.

2024-12-18 15:08 UTC, aaaaaaaalex commented on base/Dockerfile
> +FROM scratch AS intermediate-stripped
Re: intermediate-stripped..
Prior to my changes, we build up the `scratch` image, and then the very bottom line says:

```
FROM scratch
COPY --from=source / /
```

I don't really understand this line, but it's why I've now got an `intermediate-stripped` and `source-stripped`. `intermediate-stripped` was called `source`, and `source-stripped` was the final step that I didn't fully see the point of, but tried to preserve.

I can ditch that last copy to a redundant scratch if you're confident it _is_ redundant!

2024-12-18 15:59 UTC, hjiawei commented
I once tried the dnf [`--installroot` flag](https://dnf.readthedocs.io/en/latest/command_ref.html) and installed glibc only. It gives an ~4MB image and also scannable. It ships way less dependencies then ubi-minimal (size similar to alpine).

2025-01-03 02:09 UTC, hjiawei commented on images/calico-base/Dockerfile
> +RUN rm -rf /rootfs
This step results an extra layer to the source-unstripped image and wasted space if not squashed.

2025-01-03 13:41 UTC, aaaaaaaalex commented on images/calico-base/Dockerfile
> +RUN rm -rf /rootfs
IMO I think that's fine - we dont intend to ship unstripped images, and anyone who want's to build an unstripped image themselves can opt to squash.

I have cleaned up these lines a bit anyway though, and removed what I believe are redundant layers. Does this help?

2025-01-06 14:07 UTC, hjiawei commented
Do we still need this change once https://github.com/projectcalico/calico/pull/9678 is merged?

2025-01-06 14:26 UTC, aaaaaaaalex commented
@hjiawei yep

2025-01-06 14:42 UTC, hjiawei commented
> @hjiawei yep

I am not following. With your change in https://github.com/projectcalico/calico/pull/9678, is it true that a user can run the following command to switch to a different base. Is this essentially what you are doing here?

```bash
CALICO_BASE=registry.access.redhat.com/ubi8/ubi-minimal:latest make image
```

2025-01-09 15:25 UTC, fasaxc requested changes

2025-01-09 15:25 UTC, fasaxc commented on images/calico-base/Dockerfile
> +RUN rm -rf /rootfs
I think we've ended up with qemu in the image too, which we don't want and maybe we now have literally nothing of value in the unstripped image (I thought we needed to add /tmp and the licenses, but if not, perhaps we should derive it from the BASE with no changes?

2025-01-09 15:25 UTC, fasaxc commented on images/calico-base/Dockerfile
>  RUN mkdir -p /rootfs/lib64 /rootfs/etc
I think all this rootfs building (and the qemu bit) should happen in an intermediate image that's _not_ a base for the unstripped one.

2025-01-10 08:09 UTC, closed without merging